server:
  port: 8084
  servlet:
    context-path: '/mail'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=mail
      username: mail
      password: qwerty123
    rabbitmq:
      host: localhost
      port: 5672
      username: rabbit
      password: rabbit


app.basePath: /mail
order.url: http://localhost:8083/order
users.url: http://localhost:8081/users