server:
  port: 8084

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=mail
      username: mail
      password: qwerty123
    artemis:
      host: localhost
      port: 61616
      user: artemis
      password: password
      mode: native

app:basePath: /
order.url: http://localhost:8083
users.url: http://localhost:8081